mod bold_italic_unique;
mod fvar;
mod name_trailing_spaces;
mod required_tables;
mod unwanted_tables;
pub use fvar::CHECK_REGULAR_COORDS_CORRECT;
// pub use bold_italic_unique::CHECK_BOLD_ITALIC_UNIQUE;
pub use name_trailing_spaces::CHECK_NAME_TRAILING_SPACES;
pub use required_tables::CHECK_REQUIRED_TABLES;
pub use unwanted_tables::CHECK_UNWANTED_TABLES;
