mod arabic_spacing_symbols;
mod bold_italic_unique;
mod name_trailing_spaces;
mod required_tables;
mod unwanted_tables;
pub use arabic_spacing_symbols::CHECK_ARABIC_SPACING_SYMBOLS;
// pub use bold_italic_unique::CHECK_BOLD_ITALIC_UNIQUE;
pub use name_trailing_spaces::CHECK_NAME_TRAILING_SPACES;
pub use required_tables::CHECK_REQUIRED_TABLES;
pub use unwanted_tables::CHECK_UNWANTED_TABLES;
