#![allow(non_snake_case)]
mod alt_caron;
mod arabic_high_hamza;
mod arabic_spacing_symbols;
mod base_has_width;
mod case_mapping;
mod cjk_chws_feature;
mod cjk_not_enough_glyphs;
mod cmap_format_12;
mod color_cpal_brightness;
mod consistent_axes;
mod contour_count;
mod control_chars;
mod empty_glyph_on_gid1_for_colrv0;
mod empty_letters;
mod family_vertical_metrics;
mod family_win_ascent_and_descent;
mod file_size;
#[cfg(not(target_family = "wasm"))]
mod fontdata_namecheck;
#[cfg(not(target_family = "wasm"))]
mod freetype_rasterizer;
mod fvar_name_entries;
mod gpos7;
mod gpos_kerning_info;
mod hinting_impact;
mod integer_ppem_if_hinted;
mod interpolation_issues;
mod legacy_accents;
mod ligature_carets;
mod linegaps;
mod mandatory_avar_table;
mod mandatory_glyphs;
mod math_signs_width;
mod missing_small_caps_glyphs;
mod nested_components;
mod no_mac_entries;
mod os2_metrics_match_hhea;
mod required_tables;
mod rupee;
mod sfnt_version;
mod smallcaps_before_ligatures;
mod smart_dropout;
mod soft_hyphen;
mod STAT_in_statics;
mod STAT_strings;
mod stylisticset_description;
mod tabular_kerning;
mod transformed_components;
mod typoascender_exceeds_Agrave;
mod typographic_family_name;
mod unique_glyphnames;
mod unreachable_glyphs;
mod unsupported_axes;
mod unwanted_aat_tables;
mod unwanted_tables;
mod valid_glyphnames;
mod varfont_duplexed_axis_reflow;
mod varfont_instances_in_order;
mod vtt_volt_data;
mod whitespace_glyphs;
mod whitespace_ink;
mod whitespace_widths;

pub mod name;

pub use alt_caron::alt_caron;
pub use arabic_high_hamza::arabic_high_hamza;
pub use arabic_spacing_symbols::arabic_spacing_symbols;
pub use base_has_width::base_has_width;
pub use case_mapping::case_mapping;
pub use cjk_chws_feature::cjk_chws_feature;
pub use cjk_not_enough_glyphs::cjk_not_enough_glyphs;
pub use cmap_format_12::cmap_format_12;
pub use color_cpal_brightness::color_cpal_brightness;
pub use consistent_axes::consistent_axes;
pub use contour_count::contour_count;
pub use control_chars::control_chars;
pub use empty_glyph_on_gid1_for_colrv0::empty_glyph_on_gid1_for_colrv0;
pub use empty_letters::empty_letters;
pub use family_vertical_metrics::family_vertical_metrics;
pub use family_win_ascent_and_descent::family_win_ascent_and_descent;
pub use file_size::file_size;
#[cfg(not(target_family = "wasm"))]
pub use fontdata_namecheck::fontdata_namecheck;
#[cfg(not(target_family = "wasm"))]
pub use freetype_rasterizer::freetype_rasterizer;
pub use fvar_name_entries::fvar_name_entries;
pub use gpos7::gpos7;
pub use gpos_kerning_info::gpos_kerning_info;
pub use hinting_impact::hinting_impact;
pub use integer_ppem_if_hinted::integer_ppem_if_hinted;
pub use interpolation_issues::interpolation_issues;
pub use legacy_accents::legacy_accents;
pub use ligature_carets::ligature_carets;
pub use linegaps::linegaps;
pub use mandatory_avar_table::mandatory_avar_table;
pub use mandatory_glyphs::mandatory_glyphs;
pub use math_signs_width::math_signs_width;
pub use missing_small_caps_glyphs::missing_small_caps_glyphs;
pub use nested_components::nested_components;
pub use no_mac_entries::no_mac_entries;
pub use os2_metrics_match_hhea::os2_metrics_match_hhea;
pub use required_tables::required_tables;
pub use rupee::rupee;
pub use sfnt_version::sfnt_version;
pub use smallcaps_before_ligatures::smallcaps_before_ligatures;
pub use smart_dropout::smart_dropout;
pub use soft_hyphen::soft_hyphen;
pub use STAT_in_statics::STAT_in_statics;
pub use STAT_strings::STAT_strings;
pub use stylisticset_description::stylisticset_description;
pub use tabular_kerning::tabular_kerning;
pub use transformed_components::transformed_components;
pub use typoascender_exceeds_Agrave::typoascender_exceeds_Agrave;
pub use typographic_family_name::typographic_family_name;
pub use unique_glyphnames::unique_glyphnames;
pub use unreachable_glyphs::unreachable_glyphs;
pub use unsupported_axes::unsupported_axes;
pub use unwanted_aat_tables::unwanted_aat_tables;
pub use unwanted_tables::unwanted_tables;
pub use valid_glyphnames::valid_glyphnames;
pub use varfont_duplexed_axis_reflow::varfont_duplexed_axis_reflow;
pub use varfont_instances_in_order::varfont_instances_in_order;
pub use vtt_volt_data::vtt_volt_data;
pub use whitespace_glyphs::whitespace_glyphs;
pub use whitespace_ink::whitespace_ink;
pub use whitespace_widths::whitespace_widths;
