#![allow(non_snake_case)]
mod caret_slope;
mod code_pages;
mod family_naming_recommendations;
mod font_version;
mod fsselection;
mod GDEF_mark_chars;
mod GDEF_non_mark_chars;
mod GDEF_spacing_marks;
mod glyf_non_transformed_duplicate_components;
mod glyf_unused_data;
mod italic_angle;
mod layout_valid_feature_tags;
mod layout_valid_language_tags;
mod layout_valid_script_tags;
mod mac_style;
mod maxadvancewidth;
mod monospace;
mod points_out_of_bounds;
mod post_table_version;
mod postscript_name;
mod slant_direction;
mod unitsperem;
mod vendor_id;
mod xavgcharwidth;
mod weight_class_fvar;

pub mod family;
pub mod fvar;
pub mod kern_table;
pub mod loca;
pub mod name;
pub mod STAT;
pub mod varfont;

pub use caret_slope::caret_slope;
pub use code_pages::code_pages;
pub use family_naming_recommendations::family_naming_recommendations;
pub use font_version::font_version;
pub use fsselection::fsselection;
pub use GDEF_mark_chars::GDEF_mark_chars;
pub use GDEF_non_mark_chars::GDEF_non_mark_chars;
pub use GDEF_spacing_marks::GDEF_spacing_marks;
pub use glyf_non_transformed_duplicate_components::glyf_non_transformed_duplicate_components;
pub use glyf_unused_data::glyf_unused_data;
pub use italic_angle::italic_angle;
pub use layout_valid_feature_tags::layout_valid_feature_tags;
pub use layout_valid_language_tags::layout_valid_language_tags;
pub use layout_valid_script_tags::layout_valid_script_tags;
pub use mac_style::mac_style;
pub use maxadvancewidth::maxadvancewidth;
pub use monospace::monospace;
pub use points_out_of_bounds::points_out_of_bounds;
pub use post_table_version::post_table_version;
pub use postscript_name::postscript_name;
pub use slant_direction::slant_direction;
pub use unitsperem::unitsperem;
pub use vendor_id::vendor_id;
pub use xavgcharwidth::xavgcharwidth;
pub use weight_class_fvar::weight_class_fvar;
